spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 60
      max-lifetime: 1800000
      connection-timeout: 3000
      leak-detection-threshold: 60000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.springframework: warn
    com.site.xidong: info
    org.springframework.security: warn
    com.zaxxer.hikari: warn
    org.hibernate.SQL: warn
    org.springframework.transaction: warn

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

claude:
  mock:
    enabled: false

whisper:
  python:
    path: ${WHISPER_PYTHON_PATH}
  script:
    path: ${WHISPER_SCRIPT_PATH}
  mock:
    enabled: false